### ISSUE TITLE
I get "Killed" message when reading methylation data

### ISSUE THREAD

**Issue by hashimsayed0** [zhangxiaoyu11/OmiEmbed#1]
As you know, methylation data for pan-cancer is about 67 GB and reading them results in the process getting killed. Is there a workaround to this issue?

Thank you.

**Comment by zhangxiaoyu11** [comment]
Hi, sorry for the delay. Please try to upgrade your memory or use the built-in data separation for methylation data.

**Comment by zhangxiaoyu11** [comment]
> As you know, methylation data for pan-cancer is about 67 GB and reading them results in the process getting killed. Is there a workaround to this issue?
> 
> Thank you.

Hi, sorry for the delay. Please try to upgrade your memory or use the built-in data separation for methylation data.
